### PR TITLE
Add support for requestData

### PR DESCRIPTION
**Pull request by yanivamram**
Hey,
I have added the method for requestData
On my environment it works fine and already deployed to our CI Testing environment.

Thank you for sharing this great repo :-)

Yaniv

### CODE REVIEW

**Comment by shibupanda** [comment]
@yanivamram Thanks for the PR. Could you please add an example.

**Comment by yanivamram** [comment]
> @yanivamram Thanks for the PR. Could you please add an example.

Sure.
The basic example for the documentation might be:
`driver.execute_script("flutter:requestData", <request_data>)`

In our project, we are using the requestData to invoke a deepLink.
So it looks like:
`driver.execute_script("flutter:requestData", json.dumps({"deepLink": "myapp://item/id1"}))`

Plmk if further information is needed :-)

Yaniv

**Comment by KazuCocoa** [comment]
I would add the example in https://github.com/truongsinh/appium-flutter-driver 's `requestData` section to show users the method is supported

**Comment by yanivamram** [comment]
> I would add the example in https://github.com/truongsinh/appium-flutter-driver 's `requestData` section to show users the method is supported

Sure, do you want me to add it? or you're on it?

**Review by KazuCocoa — APPROVED** [review]
lgtm :)

**Comment by yanivamram** [comment]
> lgtm :)

Cool :-)
What should be done now? who may merge the PR?

**Comment by KazuCocoa** [comment]
@shibupanda can merge this

**Comment by yanivamram** [comment]
Thanks again for this repo!
I have some more useful enhancements, will share a PR next week.

Yaniv

**Pull request merged**
