### PR TITLE
Added Clear method in driver

### PR DESCRIPTION
**Pull request by shibupanda**
Now user can use existing clear method to clear the text field.
Linked Issue: https://github.com/truongsinh/appium-flutter-driver/issues/47

### CODE REVIEW

**Comment by shibupanda** [comment]
@truongsinh I will do that.
I thought to add after this pull request but no worries I have the sample code added on it.

**Comment by truongsinh** [comment]
> @truongsinh I will do that.
> I thought to add after this pull request but no worries I have the sample code added on it.

I would prefer to have it incorporated into this PR. We're not fully unit-test-covered yet, but having the simple code in the example can at least provide a way for manually verify that our code is not broken when sth new is added

**Comment by shibupanda** [comment]
@truongsinh Thanks for the guidance. 
I will take care of it from the next pull request.
I will add the complete information about the clear method today EOD.

**Comment by ahashmi24** [comment]
@shibupanda 
What would be the syntax of clear text api for Java binding?

**Comment by shibupanda** [comment]
@ahashmi24 
find.text("I can enter text").clear(); should help you.

**Pull request merged**
