### PR TITLE
modify bug on _by_ancestor_or_descendant function

### PR DESCRIPTION
**Pull request by yjf0824**
Original code of construct command as following:
```
        finder = FlutterFinder()
        key_finder = finder.by_value_key("video_name_skip")
        sub_key_finder = finder.by_value_key("txt_skip")
        final_finder = finder.by_descendant(key_finder, sub_key_finder)
        ele=FlutterElement(driver, final_finder)
        print(ele.text)

```

output:
[debug] [FlutterDriver] Executing Flutter driver command 'getText'
[debug] [FlutterDriver] >>>{"command":"get_text","finderType":"Descendant","matchRoot":false,"of_finderType":"ByValueKey","of_keyValueString":"video_name_skip","of_keyValueType":"String","matching_finderType":"ByValueKey","matching_keyValueString":"txt_skip","matching_keyValueType":"String"}
[debug] [FlutterDriver] <<< {"isError":true,"response":"Uncaught extension error while executing get_text: Null check operator used on a null value\n#0 Descendant.deserialize (package:flutter_driver/src/common/find.dart:310:55)\n#1 DeserializeFinderFactory.deserializeFinder (package:flutter_driver/src/common/deserialization_factory.dart:32:44)\n#2 FlutterDriverExtension.deserializeFinder (package:flutter_driver/src/extension/extension.dart:405:18)\n#3 new CommandWithTarget.deserialize (package:flutter_driver/src/common/find.dart:32:30)\n#4 new GetText.deserialize (package:flutter_driver/src/common/text.dart:15:97)\n#5 DeserializeCommandFactory.deserializeCommand (package:flutter_driver/src/common/deserialization_factory.dart:49:39)\n#6 FlutterDriverExtension.deserializeCommand (package:flutter_driver/src/extension/extension.dart:425:18)\n#7 FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:371:31)\n#8 BindingBase.registerServiceExtension. (package:flutter/src/foundation/binding.dart:597:32)\n\n","type":"_extensionType","method":"ext.flutter.driver"} | previous command get_text
[debug] [MJSONWP (ae86ce36)] Encountered internal error running command: Error: Cannot execute command get_text, server reponse {
[debug] [MJSONWP (ae86ce36)] "isError": true,
[debug] [MJSONWP (ae86ce36)] "response": "Uncaught extension error while executing get_text: Null check operator used on a null value\n#0 Descendant.deserialize (package:flutter_driver/src/common/find.dart:310:55)\n#1 DeserializeFinderFactory.deserializeFinder (package:flutter_driver/src/common/deserialization_factory.dart:32:44)\n#2 FlutterDriverExtension.deserializeFinder (package:flutter_driver/src/extension/extension.dart:405:18)\n#3 new CommandWithTarget.deserialize (package:flutter_driver/src/common/find.dart:32:30)\n#4 new GetText.deserialize (package:flutter_driver/src/common/text.dart:15:97)\n#5 DeserializeCommandFactory.deserializeCommand (package:flutter_driver/src/common/deserialization_factory.dart:49:39)\n#6 FlutterDriverExtension.deserializeCommand (package:flutter_driver/src/extension/extension.dart:425:18)\n#7 FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:371:31)\n#8 BindingBase.registerServiceExtension. (package:flutter/src/foundation/binding.dart:597:32)\n\n",
[debug] [MJSONWP (ae86ce36)] "type": "_extensionType",
[debug] [MJSONWP (ae86ce36)] "method": "ext.flutter.driver"
[debug] [MJSONWP (ae86ce36)] }
[debug] [MJSONWP (ae86ce36)] at FlutterDriver.exports.executeElementCommand (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:126:11)
[debug] [MJSONWP (ae86ce36)] at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] [MJSONWP (ae86ce36)] at FlutterDriver.exports.getText (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/commands/element.ts:4:20)

Compared with flutter driver locally:
VMServiceFlutterDriver: >>> {command: tap, finderType: Descendant, of: {"finderType":"ByValueKey","keyValueString":"video_name_skip","keyValueType":"String"}, matching: {"finderType":"ByValueKey","keyValueString":"txt_skip","keyValueType":"String"}, matchRoot: false, firstMatchOnly: false}

Above error may be raised by following code segment of find.dart:
final Map<String, String> jsonOfMatcher =
        Map<String, String>.from(jsonDecode(json['of']!) as Map<String, dynamic>);
final Map<String, String> jsonMatchingMatcher =
        Map<String, String>.from(jsonDecode(json['matching']!) as Map<String, dynamic>);

So may be _by_ancestor_or_descendant should be updated.

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Thank you.
Does this work well? and which flutter_driver version?
(I haven't tried this method, so I'd like to confirm)

Then, other clients also need to update because my original implementation was from https://github.com/truongsinh/appium-flutter-driver/blob/master/finder/nodejs/lib/serializer_test.ts (test code) and its code.
The implementation was wrong since the beginning or it was changed in some version of flutter.

**Comment by yjf0824** [comment]
@KazuCocoa 
It works(both ancestor and descendant) under my environment. I'm not familiar to other language. :(
My flutter environment listed as following:
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (10 days ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**Comment by KazuCocoa** [comment]
Ok, thanks for your checking!! Very appreciate. @yjf0824 

No problem with other languages. I'll update them as possible.
Then, I'll address the versions. (Thanks for this version stuff as well.)

I'll push a new python version after adding this change to master.

@shibupanda Btw, could you add me as collaborator so that I can merge this to master?

**Review by KazuCocoa — APPROVED** [review]

**Comment by KazuCocoa** [comment]
0.1.5 has this change.

**Pull request merged**
