### PR TITLE
Fixes: "kotlinx-serialization-runtime" dependency error and Added duration for wait command

### PR DESCRIPTION
**Pull request by shibupanda**
Fixes for below issue
https://github.com/truongsinh/appium-flutter-driver/issues/41

### CODE REVIEW

**Comment by truongsinh** [comment]
@shibupanda this change only affects the example. Should we do such that it is applied to the finder itself?

**Comment by shibupanda** [comment]
@truongsinh definitely let me try to build the kotlin jar having serilization runtime 0.14 build.

It's really helps if you can share the environment details for kotlin and build command so that I can test it as well.

**Comment by truongsinh** [comment]
Here's my java runtime:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

For Kotlin, I don't have it installed in the environment, I just have it installed via dependencies, in this case 
version `1.34.0` https://github.com/truongsinh/appium-flutter-driver/blob/master/finder/kotlin/build.gradle.kts#L10

**Comment by shibupanda** [comment]
Could it be possible that Maven (pom.xml) is not compatible with Gradle?
May be

But let me check I have built the jar having "kotlinx-serialization-runtime v0.14.0" . 
Testing in progress

**Comment by shibupanda** [comment]
@truongsinh looks like Maven is not compatible with gradle.
So it is not retrieving the jar in the maven local repository. And the same is happening for whaterver dependencies we have added in https://github.com/truongsinh/appium-flutter-driver/blob/fb3aa42149e245bd86b5593cb5ef57d769d02e2f/finder/kotlin/build.gradle.kts#L20

image

**Comment by shibupanda** [comment]
@truongsinh Got the fixes. I will update the commit soon.

**Comment by shibupanda** [comment]
@truongsinh added argument in waitFor and waitForAbsent function by default it is 10 * 1000 ms if it is undefined.
Fixes done for kotlin finder (tested working as expected), it is retrieving the jar from maven central and added into .m2 folder (local repository).
In previous build it failed and .m2 folder didn't contain the dependency jar.

Old Kotlin Build:
============
image

image


New Build with the changes:
======================
image

**Comment by pradarttana-sharechat** [comment]
eagerly waiting for this fix. I am trying to run appium flutter driver in a real ios device. :)

**Comment by shibupanda** [comment]
cc @truongsinh

**Comment by truongsinh** [comment]
@shibupanda thanks again for your contribution. However, it's better to have each PR to address separate issue (single-responsibility principle applies not only in classes :D)
I will try to "isolate the code" used for "kotlinx-serialization-runtime" first, and either of us can open the 2nd PR for wait command

**Comment by truongsinh** [comment]
These 2 has been merged by #51 and #52, all credits to @shibupanda

**Pull request closed without merging**
